version: '3'
services:
  db:
    image: postgres:14
    container_name: nest_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: miramax92
      POSTGRES_DB: playground
      DATABASE_HOST: db
      DATABASE_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432

  app:
    build: .
    container_name: nest_app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: ${{ secrets.FLY_API_TOKEN }}
      DATABASE_NAME: playground
      SECRET_KEY: dadwdadsacdk3qrl2jrb2l3jfnlk32nfl2nfjk2bf4wf4fw42rt42gt42gwegfwefwe23fwefsdf
    volumes:
      - .:/app
    command: npm run start:prod

volumes:
  postgres-data:
